# Generated by Django 4.2.2 on 2023-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('curriculo', models.FileField(upload_to='curriculos/')),
            ],
        ),
    ]
